FROM node:20 AS build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

FROM nginx:alpine

# 1. Limpa a pasta padrão do Nginx para evitar conflitos
RUN rm -rf /usr/share/nginx/html/*

# 2. Copia os arquivos mantendo o caminho exato do seu print (FrontEnd com F e E maiúsculos)
COPY --from=build /app/dist/FrontEnd/browser /usr/share/nginx/html

# 3. Altera o index.csr.html para index.html dentro do container
RUN mv /usr/share/nginx/html/index.csr.html /usr/share/nginx/html/index.html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]