# build
FROM node:18 AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# IMPORTANTE: build de produção
RUN npm run build -- --configuration production

# runtime
FROM nginx:alpine

# remove config default
RUN rm /etc/nginx/conf.d/default.conf

# copia config custom
COPY nginx.conf /etc/nginx/conf.d/default.conf


COPY --from=build /app/dist/BANDTADS /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]