server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: cliente-service
          uri: http://backend:8080
          predicates:
            - Path=/clientes/**
          filters:
            - StripPrefix=1