spring.application.name=auth-service
server.port=8080

spring.data.mongodb.uri=mongodb://mongo-auth:27017/authdb
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:rabbitmq}

jwt.secret=${JWT_SECRET:bantads-jwt-secret-key-minimo-32-chars}
