spring.application.name=auth-service
server.port=8080

spring.data.mongodb.uri=mongodb://mongo-auth:27017/authdb
jwt.secret=troque-este-segredo-por-uma-chave-com-no-minimo-32-bytes

spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest