spring.application.name=conta-service
server.port=8080

# Datasource ESCRITA (PostgreSQL - db-conta)
app.datasource.write.url=${CONTA_WRITE_URL:jdbc:postgresql://db-conta:5432/conta_db}
app.datasource.write.driver-class-name=org.postgresql.Driver
app.datasource.write.username=${CONTA_WRITE_USER:root}
app.datasource.write.password=${CONTA_WRITE_PASS:root}

# Datasource LEITURA (PostgreSQL - db-conta-read, ou mesmo db-conta se não tiver réplica)
app.datasource.read.url=${CONTA_READ_URL:jdbc:postgresql://db-conta-read:5432/conta_db}
app.datasource.read.driver-class-name=org.postgresql.Driver
app.datasource.read.username=${CONTA_READ_USER:root}
app.datasource.read.password=${CONTA_READ_PASS:root}

# RabbitMQ
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:rabbitmq}
spring.rabbitmq.port=5672

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true