drop table if exists movimentacao;
drop table if exists conta;

create table conta (
	id integer generated by default as identity primary key,
	cliente_id integer not null,
	numero_conta varchar(32) not null unique,
	data_criacao timestamp not null,
	saldo decimal(19,2) not null,
	limite decimal(19,2) not null,
	gerente_id integer
);

create table movimentacao (
	id integer generated by default as identity primary key,
	conta_id integer not null,
	data_hora timestamp not null,
	tipo varchar(32) not null,
	cliente_origem_id integer,
	cliente_destino_id integer,
	valor decimal(19,2) not null
);

insert into conta (cliente_id, numero_conta, data_criacao, saldo, limite, gerente_id) values
(1, '000001-00001', timestamp '2026-01-01 10:00:00', 800.00, 5000.00, 10),
(2, '000002-00002', timestamp '2026-01-01 10:00:00', 1000.00, 2500.00, 11);

insert into movimentacao (conta_id, data_hora, tipo, cliente_origem_id, cliente_destino_id, valor) values
(1, timestamp '2026-01-01 10:00:00', 'DEPOSITO', 1, 1, 1000.00),
(1, timestamp '2026-01-02 10:00:00', 'SAQUE', 1, 1, 200.00);