drop table if exists movimentacao;
drop table if exists conta;

create table conta (
	id integer generated by default as identity primary key,
	cliente_id integer not null,
	cpf varchar(32),
	numero_conta varchar(32) not null unique,
	data_criacao timestamp not null,
	saldo decimal(19,2) not null,
	limite decimal(19,2) not null,
	gerente_id integer
);

create table movimentacao (
	id integer generated by default as identity primary key,
	conta_id integer not null,
	data_hora timestamp not null,
	tipo varchar(32) not null,
	cliente_origem_id integer,
	cliente_destino_id integer,
	valor decimal(19,2) not null
);

insert into conta (cliente_id, cpf, numero_conta, data_criacao, saldo, limite, gerente_id) values
(1, '123.456.789-05', '1291', TIMESTAMP '2000-01-01 00:00:00',     800.00,  5000.00, 1),  -- Catharyna / Geniéve
(2, '123.456.789-06', '0950', TIMESTAMP '1990-10-10 00:00:00', -10000.00, 10000.00, 2),  -- Cleuddônio / Godophredo
(3, '123.456.789-07', '8573', TIMESTAMP '2012-12-12 00:00:00',  -1000.00,  1500.00, 3),  -- Catianna / Gyândula
(4, '123.456.789-08', '5887', TIMESTAMP '2022-02-22 00:00:00', 150000.00,     0.00, 1),  -- Cutardo / Geniéve
(5, '123.456.789-09', '7617', TIMESTAMP '2025-01-01 00:00:00',   1500.00,     0.00, 2);  -- Coândrya / Godophredo

insert into movimentacao (conta_id, data_hora, tipo, cliente_origem_id, cliente_destino_id, valor) values

-- Catharyna
(1, TIMESTAMP '2020-01-01 10:00:00', 'DEPOSITO',      1,    1,    1000.00),
(1, TIMESTAMP '2020-01-01 11:00:00', 'DEPOSITO',      1,    1,     900.00),
(1, TIMESTAMP '2020-01-01 12:00:00', 'SAQUE',         1,    1,     550.00),
(1, TIMESTAMP '2020-01-01 13:00:00', 'SAQUE',         1,    1,     350.00),
(1, TIMESTAMP '2020-01-10 15:00:00', 'DEPOSITO',      1,    1,    2000.00),
(1, TIMESTAMP '2020-01-15 08:00:00', 'SAQUE',         1,    1,     500.00),
(1, TIMESTAMP '2020-01-20 12:00:00', 'TRANSFERENCIA', 1,    2,    1700.00),

-- Cleuddônio
(2, TIMESTAMP '2025-01-01 12:00:00', 'DEPOSITO',      2,    2,    1000.00),
(2, TIMESTAMP '2025-01-02 10:00:00', 'DEPOSITO',      2,    2,    5000.00),
(2, TIMESTAMP '2025-01-10 10:00:00', 'SAQUE',         2,    2,     200.00),
(2, TIMESTAMP '2025-02-05 10:00:00', 'DEPOSITO',      2,    2,    7000.00),

-- Catianna
(3, TIMESTAMP '2025-05-05 00:00:00', 'DEPOSITO',      3,    3,    1000.00),
(3, TIMESTAMP '2025-05-06 00:00:00', 'SAQUE',         3,    3,    2000.00),

-- Cutardo
(4, TIMESTAMP '2025-06-01 00:00:00', 'DEPOSITO',      4,    4,  150000.00),

-- Coândrya
(5, TIMESTAMP '2025-07-01 00:00:00', 'DEPOSITO',      5,    5,    1500.00);