CREATE TABLE IF NOT EXISTS gerente_admin (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    cpf VARCHAR(11) UNIQUE NOT NULL,
    telefone VARCHAR(11) NOT NULL,
    email VARCHAR(150) NOT NULL,
    senha VARCHAR(15) NOT NULL,
    tipo VARCHAR(10) NOT NULL
);